version: '3'

services:
  homework6:
    build: .
    ports:
      - "80:80"
    volumes: 
      - .:/var/www/html
    networks:
      - my-network6
    
  db: 
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - my-network6

  phpmyadmin:
    image: phpmyadmin:5.1.3
    restart: always
    ports:
      - 8084:80
    networks:
      - my-network6


networks:
  my-network6: 
    driver: bridge
