version: '3'

services:
  homework6:
    build: .
    ports:
      - "80:80"
    volumes: 
      - .:/var/www/html
    networks:
      - my-network
    
  db: 
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin:5.1.3
    restart: always
    ports:
      - 8083:80
    networks:
      - my-network


networks:
  my-network: 
    driver: bridge
